// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "test",
  },

  album: {
    title: "test",
  },

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
    {
      id: "track-01",
      title: "outlaw",
      visual: {
        type: "video",
        src: "https://www.youtube.com/watch?v=cpVPE_BQXEI",
        loop: false,
      },
    }
  ],
  storeUrl: "www.deathbeachstudio.com",

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
