// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "Death Beach",
  },

  album: {
    title: "Scorpian",
  },

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
    {
      id: "track-01",
      title: "Drunk On The Mic",
      src: "/tracks/track1.mp3",
      lyrics: {
        type: "timed",
        src: "/lyrics/track1.lrc",   // ← add this
      },
      visual: {
        type: "reactive",
        scene: "particles",
      },
    },
    {
      id: "track-02",
      title: "NFT Song",
      src: "/tracks/track2.mp3",
      visual: {
        type: "reactive",
        scene: "pillar",
      },
    }
  ],

  storeUrl: "https://example.com/store",

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
