// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "Artist Name",
  },

  album: {
    title: "Title",
  },

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
    {
      id: "track-01",
      title: "track one",
      src: "/tracks/track1.mp3",
      visual: {
        type: "reactive",
        scene: "translation",
      },
    },
    {
      id: "track-02",
      title: "track two",
      src: "/tracks/track2.mp3",
      visual: {
        type: "reactive",
        scene: "particles",
      },
    }
  ],

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
