// hooks/useAudioData.ts
// ─────────────────────────────────────────────────────────────────────────────
// Returns a throttled Uint8Array of frequency-bin data (~30 fps) for the
// currently-playing audio track.
//
// Source of data: precomputed `.frames.bin` files generated by
// `scripts/analyze-tracks.mjs` at build time.  Each file contains FFT
// magnitude data per frame, calibrated to match what a live Web Audio
// AnalyserNode would have produced.
//
// Why precomputed instead of a live AnalyserNode?
//   - On iPhone Safari, routing audio through Web Audio puts it in the
//     "Ringer" volume bucket, which is muted when the silent switch is on.
//     Users expect music players to play through the "Media" bucket, which
//     ignores the silent switch — and the only way to get there is to play
//     audio through an HTML <audio> element WITHOUT touching Web Audio.
//   - Solution: play through <audio> (in `useAudio.ts`, html5: true), and
//     read the precomputed frequency data from disk synchronised to playback
//     position.  Visualizer output is identical; iOS users hear music; ship.
//
// The visualizer scenes are unchanged — they still receive a Uint8Array of
// the same shape as `analyser.getByteFrequencyData()`.
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useEffect, useRef } from "react";
import { usePlaylist } from "@/hooks/usePlaylist";
import { playbackTime } from "@/lib/playbackTime";

// 16-byte file header — keep in sync with scripts/analyze-tracks.mjs
const HEADER_SIZE = 16;
const MAGIC = "LFFT";

interface FramesFile {
  binsPerFrame: number;
  fps: number;
  totalFrames: number;
  data: Uint8Array; // length = binsPerFrame * totalFrames
}

/** Parse a .frames.bin payload (ArrayBuffer) into structured form. */
function parseFramesFile(ab: ArrayBuffer): FramesFile | null {
  if (ab.byteLength < HEADER_SIZE) return null;

  const view = new DataView(ab);
  const magic = String.fromCharCode(view.getUint8(0), view.getUint8(1), view.getUint8(2), view.getUint8(3));
  if (magic !== MAGIC) return null;

  // const version = view.getUint8(4); // currently 1; reserved for future use
  const binsPerFrame = view.getUint8(5);
  const fps = view.getUint8(6);
  // byte 7 reserved
  const totalFrames = view.getUint32(8, true);
  // bytes 12–15: sampleRate (not needed by the visualizer)

  const data = new Uint8Array(ab, HEADER_SIZE, binsPerFrame * totalFrames);
  return { binsPerFrame, fps, totalFrames, data };
}

/**
 * Returns the latest frequency-bin snapshot for the current track, or `null`
 * when no audio track is loaded / its frames file failed to load.
 *
 * Visualizers consume this exactly as they did the live AnalyserNode output.
 */
export function useAudioData(): Uint8Array | null {
  const { currentTrack } = usePlaylist();
  const [audioData, setAudioData] = useState<Uint8Array | null>(null);

  // Frames file for the current track — held in a ref so the RAF loop can
  // read it without re-running the effect on each new buffer.
  const framesRef = useRef<FramesFile | null>(null);
  const rafRef = useRef<number>(0);
  const lastFrameIndexRef = useRef(-1);

  // Track-change effect: fetch the new frames file (or clear if not audio).
  useEffect(() => {
    framesRef.current = null;
    lastFrameIndexRef.current = -1;
    // Defer the state clear out of the effect body to keep React happy
    // (avoids the "cascading renders" lint rule). The RAF loop will pick
    // up new data once the fetch resolves.
    const clearTimer = setTimeout(() => setAudioData(null), 0);

    // Only audio (reactive) tracks have frames files.
    if (!currentTrack || currentTrack.visual?.type !== "reactive") return;

    const src = currentTrack.src as string;
    if (!src) return;

    const url = `${src}.frames.bin`;
    const ctrl = new AbortController();

    fetch(url, { signal: ctrl.signal })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.arrayBuffer();
      })
      .then((ab) => {
        const parsed = parseFramesFile(ab);
        if (!parsed) {
          console.warn("[Lumina] Invalid frames file for", src);
          return;
        }
        framesRef.current = parsed;
      })
      .catch((err) => {
        if (err?.name !== "AbortError") {
          // Not a hard failure — visualizer just shows stillness; audio still plays.
          console.warn("[Lumina] No frames file for", src, "—", err.message);
        }
      });

    return () => {
      clearTimeout(clearTimer);
      ctrl.abort();
    };
  }, [currentTrack]);

  // RAF loop: every animation frame, look up the data slice for the current
  // playback time and (if it changed) push it to React state.
  useEffect(() => {
    const tick = () => {
      const frames = framesRef.current;
      if (frames) {
        const idx = Math.floor(playbackTime.current * frames.fps);
        const clamped = Math.max(0, Math.min(frames.totalFrames - 1, idx));

        // Only set state when the frame index actually advances, avoiding
        // pointless re-renders during pause / between fps boundaries.
        if (clamped !== lastFrameIndexRef.current) {
          lastFrameIndexRef.current = clamped;
          const start = clamped * frames.binsPerFrame;
          // Slice into a fresh Uint8Array so React notices the reference change.
          setAudioData(frames.data.slice(start, start + frames.binsPerFrame));
        }
      }
      rafRef.current = requestAnimationFrame(tick);
    };

    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, []);

  return audioData;
}
