#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// Lumina Test Reset Script
// Run with: npm run reset-test
// ─────────────────────────────────────────────────────────────────────────────

import { writeFileSync, readdirSync, unlinkSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const RESET = "\x1b[0m";
const GREEN = "\x1b[32m";

function print(msg = "") {
  console.log(msg);
}

function success(msg) {
  print(`${GREEN}✓ ${msg}${RESET}`);
}

// ── Reset lumina.config.ts ───────────────────────────────────────────────────
const baselineConfig = `// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "Death Beach",
  },

  album: {
    title: "Scorpian",
  },

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
    {
      id: "track-01",
      title: "Drunk On The Mic",
      src: "/tracks/track1.mp3",
      lyrics: {
        type: "timed",
        src: "/lyrics/track1.lrc",   // ← add this
      },
      visual: {
        type: "reactive",
        scene: "particles",
      },
    },
    {
      id: "track-02",
      title: "NFT Song",
      src: "/tracks/track2.mp3",
      visual: {
        type: "reactive",
        scene: "pillar",
      },
    }
  ],

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
`;

const configPath = join(ROOT, "lumina.config.ts");
writeFileSync(configPath, baselineConfig, "utf-8");
success("lumina.config.ts reset to baseline");

// ── Clean up public/lyrics/ ──────────────────────────────────────────────────
const lyricsDir = join(ROOT, "public", "lyrics");
if (existsSync(lyricsDir)) {
  const files = readdirSync(lyricsDir);
  for (const file of files) {
    if (file.endsWith(".lrc") && file !== "track1.lrc") {
      unlinkSync(join(lyricsDir, file));
      success(`Removed ${file}`);
    }
  }
}

// ── Clean up public/videos/ ──────────────────────────────────────────────────
const videosDir = join(ROOT, "public", "videos");
if (existsSync(videosDir)) {
  const files = readdirSync(videosDir);
  for (const file of files) {
    if (file.endsWith(".mp4")) {
      unlinkSync(join(videosDir, file));
      success(`Removed ${file}`);
    }
  }
}

print("");
success("Test environment reset complete!");
print("");
print("Baseline state:");
print("  lumina.config.ts: 2 tracks (track-01 with timed lyrics, track-02 no lyrics)");
print("  public/lyrics/: only track1.lrc remains");
print("  public/tracks/: unchanged");
print("  public/videos/: empty");
print("");