function generateConfig({ artistName, albumTitle, trackEntries, storeUrl }) {
  const hasAlbum = albumTitle && albumTitle.trim().length > 0;
  const hasStoreUrl = storeUrl && storeUrl.trim().length > 0;

  const tracksCode = trackEntries
    .map(
      (entry, i) => {
        const id = `track-${String(i + 1).padStart(2, "0")}`;
        const title = entry.name;
        const srcLine = entry.isVideo ? "" : `      src: "/tracks/${escStr(entry.audioFile)}",\n`;
        const visualBlock = entry.isVideo
          ? `      visual: {
        type: "video",
        src: "/videos/${escStr(entry.videoFile)}",
        loop: false,
      },`
          : `      visual: {
        type: "reactive",
        scene: "particles",
      },`;
        const lyricsBlock = entry.lyricsType
          ? `\n      lyrics: {\n        type: "${entry.lyricsType}",\n        ${entry.lyricsType === "timed" ? "src" : "text"}: "${escStr(entry.lyricsContent)}",\n      },`
          : "";
        return `    {
      id: "${id}",
      title: "${escStr(title)}",${srcLine}${visualBlock}${lyricsBlock}
    }${i < trackEntries.length - 1 ? "," : ""}`;
      }
    )
    .join("\n");

  const albumBlock = hasAlbum
    ? `
  album: {
    title: "${escStr(albumTitle)}",
  },`
    : `
  album: null,`;

  const storeUrlBlock = hasStoreUrl
    ? `
  storeUrl: "${escStr(storeUrl)}",`
    : "";

  return `// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "${escStr(artistName)}",
  },
${albumBlock}

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
${tracksCode}
  ],${storeUrlBlock}

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
`;
}

function escStr(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}